# Generated by Django 3.1.1 on 2020-09-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('base_price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('display_type', models.CharField(max_length=200)),
                ('display_size', models.CharField(max_length=200)),
                ('display_resolution', models.CharField(max_length=200)),
                ('refresh_rate', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('rom', models.CharField(max_length=200)),
                ('battery_capacity', models.CharField(max_length=200)),
                ('rear_cameras', models.CharField(max_length=200)),
                ('front_cameras', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=200)),
                ('charger', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('username', models.OneToOneField(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tapp.product')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tapp.user')),
            ],
        ),
    ]
