# Generated by Django 3.1.1 on 2020-09-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_auto_20200925_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='tapp.product'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='tapp.users'),
        ),
    ]
