# Generated by Django 3.1.1 on 2020-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
