# Generated by Django 3.1.1 on 2020-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0007_auto_20200926_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
