# Generated by Django 3.1.1 on 2020-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0008_auto_20200926_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=300),
        ),
    ]
